spring:
  application:
    name: ftf-redismq
  redis:
    host: 127.0.0.1
    prot: 6379
    password:
    timeout: 1000
    database: 0
    jedis:
      pool:
       max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
       max-idle: 10 # 连接池中的最大空闲连接
       min-idle: 0
       max-wait: 100000 # 连接池最大阻塞等待时间（使用负值表示没有限制）

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
