spring:
  application:
    name: ftf-redismq
  redis:
    host: 127.0.0.1
    prot: 6379
    password:
    pool:
      max-active: 100
      max-idle: 10
      min-idle: 0
      max-wait: 100000
    timeout: 0
    database: 2

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
